### ISSUE TITLE
Report terminating with error You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by eghaire** [AsBuiltReport/AsBuiltReport.VMware.vSphere#57]
Good Afternoon, 

This is my first time trying to run this report and I'm running into an issue on mulitple vCenters that I can't seem to move past. I've tried using both the IP address as well as the FQDN of the vCenter with no success.

New-AsBuiltReport : You cannot call a method on a null-valued expression.

ModuleType Version    Name                                ExportedCommands                                                                                     
---------- -------    ----                                ----------------                                                                                     
Manifest   1.0.0      AsBuiltReport                                                                                                                            
Script     0.2.0      AsBuiltReport.Cisco.UcsManager      Invoke-AsBuiltReport.Cisco.UcsManager                                                                
Script     1.0.0      AsBuiltReport.Core                  {New-AsBuiltReport, New-AsBuiltConfig, New-AsBuiltReportConfig}                                      
Script     0.4.1      AsBuiltReport.PureStorage.FlashA... Invoke-AsBuiltReport.PureStorage.FlashArray                                                          
Script     0.4.1      AsBuiltReport.VMware.NSXv           Invoke

vSphere 6.5 Build 8815520
Powershell Version 5.1 Build 14409 Revision 1018

New-AsBuiltReport -Target 'VCNAME' -Username 'USERNAME' -Password 'PASSWORD' -Report VMware.vSphere -Format Html,Word -OutputPath 'C:\TEMP' -Timestamp

VERBOSE: [ 12:35:53:743 ] [ Document ] - Document 'VMware vSphere As Built Report - 2019-05-20_12.35.53' processing started.
VERBOSE: [ 12:35:53:844 ] [ Document ] - Setting global document options.
VERBOSE: [ 12:35:53:845 ] [ Document ] - Enabling section/heading numbering.
VERBOSE: [ 12:35:53:846 ] [ Document ] - Setting default font(s) to 'Arial'.
VERBOSE: [ 12:35:53:847 ] [ Document ] - Setting page top margin to '25.05'mm.
VERBOSE: [ 12:35:53:852 ] [ Document ] - Setting page right margin to '25.05'mm.
VERBOSE: [ 12:35:53:853 ] [ Document ] - Setting page bottom margin to '25.05'mm.
VERBOSE: [ 12:35:53:854 ] [ Document ] - Setting page left margin to '25.05'mm.
VERBOSE: [ 12:35:53:858 ] [ Document ] - Setting page size to 'A4'.
VERBOSE: [ 12:35:53:859 ] [ Document ] - Setting page orientation to 'Portrait'.
VERBOSE: [ 12:35:53:861 ] [ Document ] - Setting page height to '297'mm.
VERBOSE: [ 12:35:53:863 ] [ Document ] - Setting page width to '210'mm.
VERBOSE: [ 12:35:53:864 ] [ Document ] - Setting document style 'Title'.
VERBOSE: [ 12:35:53:870 ] [ Document ] - Setting document style 'Title2'.
VERBOSE: [ 12:35:53:872 ] [ Document ] - Setting document style 'Title3'.
VERBOSE: [ 12:35:53:875 ] [ Document ] - Setting document style 'Heading1'.
VERBOSE: [ 12:35:53:877 ] [ Document ] - Setting document style 'Heading2'.
VERBOSE: [ 12:35:53:880 ] [ Document ] - Setting document style 'Heading3'.
VERBOSE: [ 12:35:53:888 ] [ Document ] - Setting document style 'Heading4'.
VERBOSE: [ 12:35:53:891 ] [ Document ] - Setting document style 'Heading5'.
VERBOSE: [ 12:35:53:897 ] [ Document ] - Setting document style 'H1ExcludeTOC'.
VERBOSE: [ 12:35:53:900 ] [ Document ] - Setting document style 'Normal'.
VERBOSE: [ 12:35:53:902 ] [ Document ] - Setting document style 'TOC'.
VERBOSE: [ 12:35:53:904 ] [ Document ] - Setting document style 'TableDefaultHeading'.
VERBOSE: [ 12:35:53:908 ] [ Document ] - Setting document style 'TableDefaultRow'.
VERBOSE: [ 12:35:53:913 ] [ Document ] - Setting document style 'TableDefaultAltRow'.
VERBOSE: [ 12:35:53:916 ] [ Document ] - Setting document style 'Critical'.
VERBOSE: [ 12:35:53:918 ] [ Document ] - Setting document style 'Warning'.
VERBOSE: [ 12:35:53:920 ] [ Document ] - Setting document style 'Info'.
VERBOSE: [ 12:35:53:922 ] [ Document ] - Setting document style 'OK'.
VERBOSE: [ 12:35:53:925 ] [ Document ] - Setting table style 'TableDefault'.
VERBOSE: [ 12:35:53:928 ] [ Document ] - Setting table style 'Borderless'.
VERBOSE: [ 12:35:53:930 ] [ Document ] - Processing blank line.
VERBOSE: [ 12:35:53:932 ] [ Document ] - Processing paragraph 'VMware vSphere As Built Report'.
VERBOSE: [ 12:35:53:934 ] [ Document ] - Processing blank line.
VERBOSE: [ 12:35:53:937 ] [ Document ] - Processing table 'Cover Page'.
VERBOSE: [ 12:35:53:940 ] [ Document ] - Processing page break.
VERBOSE: [ 12:35:53:947 ] [ Document ] - Processing table of contents 'Table of Contents'.
VERBOSE: [ 12:35:53:950 ] [ Document ] - Processing page break.
VERBOSE: [ 12:36:04:950 ] [ Document ] - Processing section '***' started.
VERBOSE: [ 12:36:04:992 ] [ Document ] - Processing section 'vCenter Server' started.
VERBOSE: [ 12:36:05:005 ] [ Document ] - Processing paragraph 'The following section provides infor[..]'.
VERBOSE: [ 12:36:05:006 ] [ Document ] - Processing blank line.
VERBOSE: [ 12:36:05:355 ] [ Document ] - Processing table 'redacted vCenter Server Detailed Information'.
VERBOSE: [ 12:36:05:406 ] [ Document ] - Processing section 'Database Settings' started.
VERBOSE: [ 12:36:05:471 ] [ Document ] - Processing table 'redacted vCenter Server Database Configuration'.
VERBOSE: [ 12:36:05:494 ] [ Document ] - Processing section 'Database Settings' completed.
VERBOSE: [ 12:36:05:498 ] [ Document ] - Processing section 'Mail Settings' started.
VERBOSE: [ 12:36:05:600 ] [ Document ] - Processing table 'redacted vCenter Server Mail Configuration'.
VERBOSE: [ 12:36:05:611 ] [ Document ] - Processing section 'Mail Settings' completed.
VERBOSE: [ 12:36:05:613 ] [ Document ] - Processing section 'Historical Statistics' started.
VERBOSE: [ 12:36:06:417 ] [ Document ] - Processing table 'redacted vCenter Server vHistorical Statistics'.
VERBOSE: [ 12:36:06:457 ] [ Document ] - Processing section 'Historical Statistics' completed.
VERBOSE: [ 12:36:06:460 ] [ Document ] - Processing section 'Licensing' started. 
New-AsBuiltReport : You cannot call a method on a null-valued expression.
At line:1 char:1
+ New-AsBuiltReport -Target 'redacted' -User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by tpcarman** [comment]
This issue should be resolved in the latest AsBuiltReport.VMware.vSphere module. There is also an update available for the core module. Apply the updates and let me know if this resolves your issue. 

```PowerShell
Update-Module -Name AsBuiltReport.Core -RequiredVersion 1.0.1
Update-Module -Name AsBuiltReport.VMware.vSphere -RequiredVersion 1.0.6
```

**Comment by eghaire** [comment]
> This issue should be resolved in the latest AsBuiltReport..vSphere module. There is also an update available for the core module. Apply the updates and let me know if this resolves your issue.
> 
> ```powershell
> Update-Module -Name AsBuiltReport.Core -RequiredVersion 1.0.1
> Update-Module -Name AsBuiltReport.VMware.vSphere -RequiredVersion 1.0.6
> ```

**Comment by eghaire** [comment]
Looks like upgrading it did resolve the problem. Thank you for the great support and great tool.

**Comment by eghaire** [comment]
Hey Tim, 

I'm still getting an error message when we try and run the report. Below is the latest error and version information. I'm sure this is user error but I wanted to double check. 

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Manifest   1.0.2      AsBuiltReport                                                                                                                                                                                                                              
Script     0.2.1      AsBuiltReport.Cisco.UcsManager      Invoke-AsBuiltReport.Cisco.UcsManager                                                                                                                                                                  
Script     1.0.1      AsBuiltReport.Core                  {New-AsBuiltReport, New-AsBuiltConfig, New-AsBuiltReportConfig}                                                                                                                                        
Script     0.4.1      AsBuiltReport.PureStorage.FlashA... Invoke-AsBuiltReport.PureStorage.FlashArray                                                                                                                                                            
Script     0.4.1      AsBuiltReport.VMware.NSXv           Invoke-AsBuiltReport.VMware.NSXv                                                                                                                                                                       
Script     1.0.6      AsBuiltReport.VMware.vSphere        Invoke-AsBuiltReport.VMware.vSphere                                                                                                                                                                    


VERBOSE: [ 10:46:08:181 ] [ Document ] - Processing blank line.
Get-VMHostNetworkAdapter : 6/19/2019 10:46:08 AM       Get-VMHostNetworkAdapter          Value cannot be null.
Parameter name: key  
At C:\Program Files\WindowsPowerShell\Modules\AsBuiltReport.VMware.vSphere\1.0.6\Src\Public\Invoke-AsBuiltReport.VMware.vSphere.ps1:2128 char:79
+ ...      $VMkernelAdapters = $VMHost | Get-VMHostNetworkAdapter -VMKernel
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VMHostNetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.Host.GetVMHostNetworkAdapter

VERBOSE: [ 10:46:08:264 ] [ Document ] - Processing table 'vcenter VMkernel Adapters'.
New-AsBuiltReport : Cannot bind argument to parameter 'Rows' because it is an empty collection.
At line:1 char:1
+ New-AsBuiltReport -Target 'vcenter' -Username user -Re ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by eghaire** [comment]
ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Manifest   1.0.2      AsBuiltReport                                                                                                                                                                                                                              
Script     0.2.1      AsBuiltReport.Cisco.UcsManager      Invoke-AsBuiltReport.Cisco.UcsManager                                                                                                                                                                  
Script     1.0.1      AsBuiltReport.Core                  {New-AsBuiltReport, New-AsBuiltConfig, New-AsBuiltReportConfig}                                                                                                                                        
Script     0.4.1      AsBuiltReport.PureStorage.FlashA... Invoke-AsBuiltReport.PureStorage.FlashArray                                                                                                                                                            
Script     0.4.1      AsBuiltReport.VMware.NSXv           Invoke-AsBuiltReport.VMware.NSXv                                                                                                                                                                       
Script     1.0.6      AsBuiltReport.VMware.vSphere        Invoke-AsBuiltReport.VMware.vSphere

**Comment by eghaire** [comment]
@tpcarman Any thoughts on what might be causing me to run into this issue?

**Comment by tpcarman** [comment]
What version of PowerCLI are you using? It looks to be an issue with `Get-VMHostNetworkAdapter`

Run the following to determine your PowerCLI version
```powershell
Get_PowerCLIVersion
```

**Comment by tpcarman** [comment]
Closing due to inactivity.
